/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem {
  'size' : string,
  'productId' : bigint,
  'quantity' : bigint,
}
export type Category = { 'Accessories' : null } |
  { 'Pants' : null } |
  { 'Shirts' : null } |
  { 'TShirts' : null };
export type ExternalBlob = Uint8Array;
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'userId' : Principal,
  'createdAt' : bigint,
  'updatedAt' : bigint,
  'items' : Array<OrderItem>,
  'adminNotes' : string,
}
export interface OrderItem {
  'name' : string,
  'size' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'price' : number,
}
export interface OrderItemInput {
  'name' : string,
  'size' : string,
  'productId' : bigint,
  'quantity' : bigint,
  'price' : number,
}
export type OrderStatus = { 'Delivered' : null } |
  { 'Confirmed' : null } |
  { 'Shipped' : null } |
  { 'Pending' : null };
export interface Product {
  'id' : bigint,
  'stockQuantity' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'sizes' : Array<string>,
  'updatedAt' : bigint,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : number,
}
export interface ProductInput {
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'sizes' : Array<string>,
  'category' : Category,
  'image' : ExternalBlob,
  'price' : number,
}
export interface SiteSettings {
  'description' : string,
  'whatsappNumber' : string,
  'shopName' : string,
  'bannerMessage' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addToCart' : ActorMethod<[bigint, string, bigint], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[Array<OrderItemInput>], Order>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getSettings' : ActorMethod<[], SiteSettings>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromCart' : ActorMethod<[bigint, string], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'updateCartItem' : ActorMethod<[bigint, string, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<
    [bigint, OrderStatus, string],
    [] | [Order]
  >,
  'updateProduct' : ActorMethod<[bigint, ProductInput], [] | [Product]>,
  'updateSettings' : ActorMethod<[SiteSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];